### ISSUE TITLE
Pins not rendering in expected place in 0.5.2

### ISSUE THREAD

**Issue by matkun** [advanced-cms/advanced-reviews#104]
It seems like there is an issue with the positioning of pins in version 0.5.2 of the add-on (see gif animation below).

We set up an Alloy website and tried the nuget packages for versions 0.5.1 (works) followed by 0.5.2  (issues). Both together with EPiServer.CMS 11.14.1. Tested in Chrome 79.0.3945.130 and Firefox 72.0.2. 

The javascript error appearing in the gif when clicking the bottom lists is:
``` 
Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null
   at Object.t.default (offset.ts:2)
   at t.addReviewLocation (iframe-overlay.tsx:95)
``` 
The error doesn't seem to happen if removing the three blocks "Sharing worldwide", "Contact us" and "Find reseller". Maybe related to scrolling.

The pin on the block "Sharing worldwide" changes location vertically when creating new pin after scrolling.

The pin being rendered on the H1-tag when clicking the heading of the orange box may be due to the two texts having the same _data-epi-property-name="PageName"_ (just guessing here).

![pins_moving_and_js_error](https://user-images.githubusercontent.com/559763/73830132-692f5480-4804-11ea-82e9-1a59e6dd6590.gif)

**Comment by barteksekula** [comment]
@matkun I assume it only happens in the "external" scenario right? Does it work fine inside Edit mode?

**Comment by barteksekula** [comment]
@matkun could you please test this PR? https://github.com/advanced-cms/advanced-reviews/pull/109 
You can either clone and checkout my branch and use the sample Alloy or clone/checkout and run pack.cmd to create a pre-release nuget that you could try to apply on your own site.

This pin positioning is quite complex matter so I would really appreciate if you could test my PR.
The problem was always about the fact that the iframe in Edit Mode is embedded in a 'viewport-like' div that is messing the calculations a bit.

**Comment by matkun** [comment]
Tested, involved my collegue in testing as well, we can't find anything wrong. Works both in Episerver's edit mode as well as in the external review context. Thanks for the fast fix :)

Tested in Firefox 72.0.2, it's same in Chrome 80.0.3987.87.
Commented here https://github.com/advanced-cms/advanced-reviews/pull/109#issuecomment-584136606

**Comment by barteksekula** [comment]
Fixed in https://nuget.episerver.com/package/?id=Advanced.CMS.AdvancedReviews&v=0.5.3

**Comment by barteksekula** [comment]
@matkun it took a while but 0.5.3 is finally out with several important bug fixes.
