### ISSUE TITLE
Unable to scroll while in review mode

### ISSUE THREAD

**Issue by philippeop** [advanced-cms/advanced-reviews#190]
We're using version 0.8.3.0 and noticed that scrolling the page vertically is only possible when the review mode is turned off.

Is intentional?

**Comment by barteksekula** [comment]
@philippeop No, of course it's not intentional.
I'm unable to reproduce in the sample Alloy. Could you please give it a shot yourself? 
Just add the nuget to any Alloy instance or git clone this repo and run https://github.com/advanced-cms/advanced-reviews#development-if-you-would-like-to-help-in-development

**Comment by philippeop** [comment]
@barteksekula Thanks for the confirmation, I investigated the issue and determined it was caused by our CSS
